[workspace]
members = ["codegen", "lib"]
resolver = "3"

[workspace.dependencies]
lemon-pkmn = { path = "lib" }
bitcode = "0.6.9"
bitflags = "2.10.0"
serde = { version = "1.0.228", features = ["derive"] }
strum = "0.27.2"
strum_macros = "0.27.2"
zstd = "0.13.3"